# Site settings
title: 
header-img: img/home-bg.png
email: humza1born@gmail.com
copyright_name: HMJospeh
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HMJospeh
learn_profile: HMJospeh
email_username: humza1born@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
